// User has to complete/click the entire sequence at each level, while the system genrates sound only for the next element in the sequence.

var buttonColors=["red","blue","green","yellow"];
var gamePattern =[]; // to keep track of sequence generated by system.
var userClickedPattern=[]; // to keep track of user clicks, initialised to empty array at every level.
var started = false; // flag to start/restart the game.
var level =0; 


$(document).keypress(function(){ // key press event to start the game
  if(!started){ 
    $("#level-title").text("Level "+ level);
    nextSequence(); 
    started= true;
  }
});

$(".btn").click(function(){ // to track userChosenColor and validate at the same time for each click
  var userChosenColor = $(this).attr("id");
  userClickedPattern.push(userChosenColor);
  playSound(userChosenColor);
  animatePress(userChosenColor);
  checkAnswer(userClickedPattern.length - 1);

});

function checkAnswer(currentLevel){
  if(gamePattern[currentLevel]===userClickedPattern[currentLevel]){ // check each user click.

  if(userClickedPattern.length===gamePattern.length){ // play the next sequence when user matches each and every click 
    setTimeout(function(){
    nextSequence();
    },1000);
  }
}
  else{ // as soon as user clicks wrong button
    playSound("wrong");
    $("body").addClass("game-over");
    $("#level-title").text("Game Over, Press Any Key to Restart");

    setTimeout(function(){
      $("body").removeClass("game-over");

    },200);
    startOver();
  }
}

function nextSequence(){ // play a single tone for next button in sequence
  userClickedPattern=[]; // initialise to empty array (why? to check the whole sequence from start.) 
  level++; // increase the level
  $("#level-title").text("Level "+ level);
  
  // choose random color and play a tone 
  var randomNumber=Math.floor(Math.random()*4);
  var randomChosenColor=buttonColors[randomNumber];
  gamePattern.push(randomChosenColor); 

  $("#"+randomChosenColor).fadeIn(100).fadeOut(100).fadeIn(100);
  playSound(randomChosenColor);

}
function playSound(name){ // play appropiate sound
  var audio = new Audio("sounds/"+ name + ".mp3");
  audio.play();
}
function animatePress(currentColor){ // add animation to click
  $("#"+currentColor).addClass("pressed");
  setTimeout(function(){
    $("#"+currentColor).removeClass("pressed");

  }, 100);

}
function startOver() { // initialise variables to start state to restart the game.
  level = 0;
  gamePattern = [];
  started = false;
}
